// Copies the IDL and TypeScript types generated by `anchor build` into the SDK.
import { copyFileSync, existsSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "sdk/src/idl");
const files = [
  ["target/idl/launchpad.json", "launchpad.json"],
  ["target/types/launchpad.ts", "launchpad.ts"],
];

mkdirSync(out, { recursive: true });
for (const [from, to] of files) {
  const src = join(root, from);
  if (!existsSync(src)) {
    console.error(`missing ${from}: run \`anchor build\` first`);
    process.exit(1);
  }
  copyFileSync(src, join(out, to));
  console.log(`${from} -> sdk/src/idl/${to}`);
}
